rm apps/token-tango-web-ui/turbo/generators/config.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/input.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/dropdown-menu.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/card.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/dialog.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/button.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/switch.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/form.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/label.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/select.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/checkbox.d.ts.map
rm apps/token-tango-web-ui/@/components/ui/alert.d.ts.map
rm apps/token-tango-web-ui/src/references/config-base.d.ts.map
rm apps/token-tango-web-ui/src/components/config.d.ts.map
rm apps/token-tango-web-ui/src/components/push.d.ts.map
rm apps/token-tango-web-ui/src/components/repository.d.ts.map
rm apps/token-tango-web-ui/src/services/repository.services.d.ts.map
rm apps/token-tango-web-ui/src/index.d.ts.map
rm apps/token-tango-widget/types/state.d.ts.map
rm apps/token-tango-widget/src/ui/components/name-format.d.ts.map
rm apps/token-tango-widget/src/ui/components/bottom-logo.d.ts.map
rm apps/token-tango-widget/src/ui/pages/loaded-page.d.ts.map
rm apps/token-tango-widget/src/ui/pages/empty-page.d.ts.map
rm apps/token-tango-widget/src/token-list/index.d.ts.map
rm apps/token-tango-widget/src/token-studio/token-studio.d.ts.map
rm apps/token-tango-widget/src/token-studio/index.d.ts.map
rm apps/token-tango-widget/src/common/component.utils.d.ts.map
rm apps/token-tango-widget/src/common/layer-diff.test.d.ts.map
rm apps/token-tango-widget/src/common/variables.utils.d.ts.map
rm apps/token-tango-widget/src/common/figma.types.d.ts.map
rm apps/token-tango-widget/src/common/token.types.d.ts.map
rm apps/token-tango-widget/src/common/github.utils.test.d.ts.map
rm apps/token-tango-widget/src/common/token-parser.utils.d.ts.map
rm apps/token-tango-widget/src/common/github.utils.d.ts.map
rm apps/token-tango-widget/src/common/generator.utils.d.ts.map
rm apps/token-tango-widget/src/common/layer-diff.utils.d.ts.map
rm apps/token-tango-widget/src/common/token-parser.types.d.ts.map
rm apps/token-tango-widget/src/common/token.utils.d.ts.map
rm apps/token-tango-widget/src/local-variable/local-variable.d.ts.map
rm apps/token-tango-widget/src/local-variable/index.d.ts.map
rm apps/token-tango-widget/src/services/load-tokens.services.d.ts.map
rm apps/token-tango-widget/src/services/load-github.services.d.ts.map
rm apps/token-tango-widget/src/constants.d.ts.map
rm packages/radius-toolkit/src/lib/configuration/configuration.types.d.ts.map
rm packages/radius-toolkit/src/lib/configuration/index.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/rules.test.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/rules.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/format.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/index.d.ts.map
rm packages/radius-toolkit/src/lib/formats/format.types.d.ts.map
rm packages/radius-toolkit/src/lib/formats/format.utils.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-simple/rules.test.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-simple/rules.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-simple/format.d.ts.map
rm packages/radius-toolkit/src/lib/formats/radius-simple/index.d.ts.map
rm packages/radius-toolkit/src/lib/formats/rules-testing.utils.d.ts.map
rm packages/radius-toolkit/src/lib/formats/format.utils.test.d.ts.map
rm packages/radius-toolkit/src/lib/formats/formats.d.ts.map
rm packages/radius-toolkit/src/lib/formats/token-name-format.types.d.ts.map
rm packages/radius-toolkit/src/lib/formats/index.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/variable.types.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/token.types.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/token-parser.utils.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/token-parser.types.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/index.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/token.utils.d.ts.map
rm packages/radius-toolkit/src/lib/tokens/token.utils.test.d.ts.map
rm packages/radius-toolkit/src/lib/index.d.ts.map
rm packages/radius-toolkit/src/cli.d.ts.map
rm packages/radius-toolkit/src/index.d.ts.map
rm packages/bandoneon/turbo/generators/config.d.ts.map
rm packages/bandoneon/src/button.d.ts.map

rm apps/token-tango-web-ui/turbo/generators/config.d.ts
rm apps/token-tango-web-ui/@/components/ui/input.d.ts
rm apps/token-tango-web-ui/@/components/ui/dropdown-menu.d.ts
rm apps/token-tango-web-ui/@/components/ui/card.d.ts
rm apps/token-tango-web-ui/@/components/ui/dialog.d.ts
rm apps/token-tango-web-ui/@/components/ui/button.d.ts
rm apps/token-tango-web-ui/@/components/ui/switch.d.ts
rm apps/token-tango-web-ui/@/components/ui/form.d.ts
rm apps/token-tango-web-ui/@/components/ui/label.d.ts
rm apps/token-tango-web-ui/@/components/ui/select.d.ts
rm apps/token-tango-web-ui/@/components/ui/checkbox.d.ts
rm apps/token-tango-web-ui/@/components/ui/alert.d.ts
rm apps/token-tango-web-ui/src/references/config-base.d.ts
rm apps/token-tango-web-ui/src/components/config.d.ts
rm apps/token-tango-web-ui/src/components/push.d.ts
rm apps/token-tango-web-ui/src/components/repository.d.ts
rm apps/token-tango-web-ui/src/services/repository.services.d.ts
rm apps/token-tango-web-ui/src/index.d.ts
rm apps/token-tango-widget/types/state.d.ts
rm apps/token-tango-widget/src/ui/components/name-format.d.ts
rm apps/token-tango-widget/src/ui/components/bottom-logo.d.ts
rm apps/token-tango-widget/src/ui/pages/loaded-page.d.ts
rm apps/token-tango-widget/src/ui/pages/empty-page.d.ts
rm apps/token-tango-widget/src/token-list/index.d.ts
rm apps/token-tango-widget/src/token-studio/token-studio.d.ts
rm apps/token-tango-widget/src/token-studio/index.d.ts
rm apps/token-tango-widget/src/common/component.utils.d.ts
rm apps/token-tango-widget/src/common/layer-diff.test.d.ts
rm apps/token-tango-widget/src/common/variables.utils.d.ts
rm apps/token-tango-widget/src/common/figma.types.d.ts
rm apps/token-tango-widget/src/common/token.types.d.ts
rm apps/token-tango-widget/src/common/github.utils.test.d.ts
rm apps/token-tango-widget/src/common/token-parser.utils.d.ts
rm apps/token-tango-widget/src/common/github.utils.d.ts
rm apps/token-tango-widget/src/common/generator.utils.d.ts
rm apps/token-tango-widget/src/common/layer-diff.utils.d.ts
rm apps/token-tango-widget/src/common/token-parser.types.d.ts
rm apps/token-tango-widget/src/common/token.utils.d.ts
rm apps/token-tango-widget/src/local-variable/local-variable.d.ts
rm apps/token-tango-widget/src/local-variable/index.d.ts
rm apps/token-tango-widget/src/services/load-tokens.services.d.ts
rm apps/token-tango-widget/src/services/load-github.services.d.ts
rm apps/token-tango-widget/src/constants.d.ts
rm packages/radius-toolkit/src/lib/configuration/configuration.types.d.ts
rm packages/radius-toolkit/src/lib/configuration/index.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/rules.test.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/rules.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/format.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/index.d.ts
rm packages/radius-toolkit/src/lib/formats/format.types.d.ts
rm packages/radius-toolkit/src/lib/formats/format.utils.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-simple/rules.test.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-simple/rules.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-simple/format.d.ts
rm packages/radius-toolkit/src/lib/formats/radius-simple/index.d.ts
rm packages/radius-toolkit/src/lib/formats/rules-testing.utils.d.ts
rm packages/radius-toolkit/src/lib/formats/format.utils.test.d.ts
rm packages/radius-toolkit/src/lib/formats/formats.d.ts
rm packages/radius-toolkit/src/lib/formats/token-name-format.types.d.ts
rm packages/radius-toolkit/src/lib/formats/index.d.ts
rm packages/radius-toolkit/src/lib/tokens/variable.types.d.ts
rm packages/radius-toolkit/src/lib/tokens/token.types.d.ts
rm packages/radius-toolkit/src/lib/tokens/token-parser.utils.d.ts
rm packages/radius-toolkit/src/lib/tokens/token-parser.types.d.ts
rm packages/radius-toolkit/src/lib/tokens/index.d.ts
rm packages/radius-toolkit/src/lib/tokens/token.utils.d.ts
rm packages/radius-toolkit/src/lib/tokens/token.utils.test.d.ts
rm packages/radius-toolkit/src/lib/index.d.ts
rm packages/radius-toolkit/src/cli.d.ts
rm packages/radius-toolkit/src/index.d.ts
rm packages/bandoneon/turbo/generators/config.d.ts
rm packages/bandoneon/src/button.d.ts


rm apps/token-tango-web-ui/turbo/generators/config.js
rm apps/token-tango-web-ui/@/components/ui/input.js
rm apps/token-tango-web-ui/@/components/ui/dropdown-menu.js
rm apps/token-tango-web-ui/@/components/ui/card.js
rm apps/token-tango-web-ui/@/components/ui/dialog.js
rm apps/token-tango-web-ui/@/components/ui/button.js
rm apps/token-tango-web-ui/@/components/ui/switch.js
rm apps/token-tango-web-ui/@/components/ui/form.js
rm apps/token-tango-web-ui/@/components/ui/label.js
rm apps/token-tango-web-ui/@/components/ui/select.js
rm apps/token-tango-web-ui/@/components/ui/checkbox.js
rm apps/token-tango-web-ui/@/components/ui/alert.js
rm apps/token-tango-web-ui/src/references/config-base.js
rm apps/token-tango-web-ui/src/components/config.js
rm apps/token-tango-web-ui/src/components/push.js
rm apps/token-tango-web-ui/src/components/repository.js
rm apps/token-tango-web-ui/src/services/repository.services.js
rm apps/token-tango-web-ui/src/index.js
rm apps/token-tango-widget/types/state.js
rm apps/token-tango-widget/src/ui/components/name-format.js
rm apps/token-tango-widget/src/ui/components/bottom-logo.js
rm apps/token-tango-widget/src/ui/pages/loaded-page.js
rm apps/token-tango-widget/src/ui/pages/empty-page.js
rm apps/token-tango-widget/src/token-list/index.js
rm apps/token-tango-widget/src/token-studio/token-studio.js
rm apps/token-tango-widget/src/token-studio/index.js
rm apps/token-tango-widget/src/common/component.utils.js
rm apps/token-tango-widget/src/common/layer-diff.test.js
rm apps/token-tango-widget/src/common/variables.utils.js
rm apps/token-tango-widget/src/common/figma.types.js
rm apps/token-tango-widget/src/common/token.types.js
rm apps/token-tango-widget/src/common/github.utils.test.js
rm apps/token-tango-widget/src/common/token-parser.utils.js
rm apps/token-tango-widget/src/common/github.utils.js
rm apps/token-tango-widget/src/common/generator.utils.js
rm apps/token-tango-widget/src/common/layer-diff.utils.js
rm apps/token-tango-widget/src/common/token-parser.types.js
rm apps/token-tango-widget/src/common/token.utils.js
rm apps/token-tango-widget/src/local-variable/local-variable.js
rm apps/token-tango-widget/src/local-variable/index.js
rm apps/token-tango-widget/src/services/load-tokens.services.js
rm apps/token-tango-widget/src/services/load-github.services.js
rm apps/token-tango-widget/src/constants.js
rm packages/radius-toolkit/src/lib/configuration/configuration.types.js
rm packages/radius-toolkit/src/lib/configuration/index.js
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/rules.test.js
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/rules.js
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/format.js
rm packages/radius-toolkit/src/lib/formats/radius-layer-subject-type/index.js
rm packages/radius-toolkit/src/lib/formats/format.types.js
rm packages/radius-toolkit/src/lib/formats/format.utils.js
rm packages/radius-toolkit/src/lib/formats/radius-simple/rules.test.js
rm packages/radius-toolkit/src/lib/formats/radius-simple/rules.js
rm packages/radius-toolkit/src/lib/formats/radius-simple/format.js
rm packages/radius-toolkit/src/lib/formats/radius-simple/index.js
rm packages/radius-toolkit/src/lib/formats/rules-testing.utils.js
rm packages/radius-toolkit/src/lib/formats/format.utils.test.js
rm packages/radius-toolkit/src/lib/formats/formats.js
rm packages/radius-toolkit/src/lib/formats/token-name-format.types.js
rm packages/radius-toolkit/src/lib/formats/index.js
rm packages/radius-toolkit/src/lib/tokens/variable.types.js
rm packages/radius-toolkit/src/lib/tokens/token.types.js
rm packages/radius-toolkit/src/lib/tokens/token-parser.utils.js
rm packages/radius-toolkit/src/lib/tokens/token-parser.types.js
rm packages/radius-toolkit/src/lib/tokens/index.js
rm packages/radius-toolkit/src/lib/tokens/token.utils.js
rm packages/radius-toolkit/src/lib/tokens/token.utils.test.js
rm packages/radius-toolkit/src/lib/index.js
rm packages/radius-toolkit/src/cli.js
rm packages/radius-toolkit/src/index.js
rm packages/bandoneon/turbo/generators/config.js
rm packages/bandoneon/src/button.js